# Generated by Django 3.0.6 on 2020-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('CEO', models.CharField(max_length=200, null=True, unique=True, verbose_name='CEO')),
            ],
            options={
                'verbose_name': 'Legal Person',
                'verbose_name_plural': 'Legal Persons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('NID', models.CharField(max_length=10, null=True, unique=True, verbose_name='National ID')),
            ],
            options={
                'verbose_name': 'Natural Person',
                'verbose_name_plural': 'Natural Persons',
                'ordering': ['name'],
            },
        ),
    ]
