# Generated by Django 3.0.6 on 2020-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalperson',
            name='CEO',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='NID',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='National ID'),
        ),
    ]
