# Generated by Django 3.0.6 on 2020-06-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0004_auto_20200602_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Person Image'),
        ),
    ]
