# Generated by Django 3.0.6 on 2020-06-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0005_auto_20200602_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='legalperson',
            name='CEO',
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shenasa.NaturalPerson', verbose_name='Person')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shenasa.Role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Person Role',
                'verbose_name_plural': 'Person Roles',
                'ordering': ['person', 'role'],
                'unique_together': {('person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='legalperson',
            name='person_role',
            field=models.ManyToManyField(to='Shenasa.PersonRole', verbose_name='Key Person'),
        ),
    ]
