# Generated by Django 3.0.6 on 2020-06-04 12:17

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0006_auto_20200603_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('link', models.TextField(blank=True, max_length=200, null=True, verbose_name='Link')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[150, 150], upload_to='media/', verbose_name='Person Image'),
        ),
    ]
