# Generated by Django 3.0.6 on 2020-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0007_auto_20200604_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role',
            field=models.CharField(choices=[('ST', 'Stackholder'), ('FN', 'Founder'), ('CF', 'Co Founder'), ('IN', 'Investor'), ('IA', 'Angel Investor'), ('IV', 'Venture Capital'), ('OW', 'Owner'), ('CE', 'Chief Executive Officer'), ('CT', 'Chief Technical Officer'), ('CC', 'Chief Communication Officer'), ('CM', 'Chief Marketing Officer'), ('CH', 'Chairman')], default='ST', max_length=10, verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
