# Generated by Django 3.0.6 on 2020-06-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0008_auto_20200605_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalperson',
            name='person_role',
            field=models.ManyToManyField(related_name='person_role', to='Shenasa.PersonRole', verbose_name='Key Person'),
        ),
    ]
