# Generated by Django 3.0.6 on 2020-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0010_legalperson_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='news',
            field=models.ManyToManyField(related_name='natural_person_news', to='Shenasa.News', verbose_name='News'),
        ),
    ]
