# Generated by Django 3.0.6 on 2020-06-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0011_naturalperson_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrole',
            name='role',
            field=models.CharField(choices=[('FN', 'Founder'), ('CH', 'Chairman'), ('IN', 'Investor'), ('IF', 'Foreign Investor'), ('IV', 'Venture Capital'), ('IA', 'Angel Investor'), ('ST', 'Stackholder'), ('AC', 'Accelerator'), ('OW', 'Owner'), ('CM', 'Chief Marketing Officer'), ('CC', 'Chief Communication Officer'), ('CE', 'Chief Executive Officer'), ('CT', 'Chief Technical Officer'), ('CF', 'Co Founder')], default='ST', max_length=10, verbose_name='Role'),
        ),
    ]
