# Generated by Django 3.0.6 on 2020-06-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0012_auto_20200608_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalperson',
            name='person_role',
            field=models.ManyToManyField(related_name='person_role', to='Shenasa.PersonRole', verbose_name='Natural Key Person'),
        ),
        migrations.CreateModel(
            name='LegalRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FN', 'Founder'), ('CH', 'Chairman'), ('IN', 'Investor'), ('IF', 'Foreign Investor'), ('IV', 'Venture Capital'), ('IA', 'Angel Investor'), ('ST', 'Stackholder'), ('AC', 'Accelerator'), ('OW', 'Owner'), ('CM', 'Chief Marketing Officer'), ('CC', 'Chief Communication Officer'), ('CE', 'Chief Executive Officer'), ('CT', 'Chief Technical Officer'), ('CF', 'Co Founder')], default='ST', max_length=10, verbose_name='Role')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shenasa.LegalPerson', verbose_name='Legal Person')),
            ],
            options={
                'verbose_name': 'Legal Role',
                'verbose_name_plural': 'Legal Roles',
                'ordering': ['person', 'role'],
                'unique_together': {('person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='legalperson',
            name='legal_role',
            field=models.ManyToManyField(related_name='legal_role', to='Shenasa.LegalRole', verbose_name='Legal Key Person'),
        ),
    ]
