# Generated by Django 3.0.6 on 2020-06-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0014_auto_20200608_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrole',
            name='amount_of_investment',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Amount of Investment (M rls)'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='number_of_shares',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Number of Shares'),
        ),
    ]
