# Generated by Django 3.0.6 on 2020-06-09 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0016_auto_20200608_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('legalperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Shenasa.LegalPerson')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
            bases=('Shenasa.legalperson',),
        ),
        migrations.AlterField(
            model_name='legalrole',
            name='amount_of_investment',
            field=models.IntegerField(default=0, verbose_name='Amount of Investment (M rls)'),
        ),
        migrations.AlterField(
            model_name='legalrole',
            name='number_of_shares',
            field=models.IntegerField(default=0, verbose_name='Number of Shares'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='amount_of_investment',
            field=models.IntegerField(default=0, verbose_name='Amount of Investment (M rls)'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='number_of_shares',
            field=models.IntegerField(default=0, verbose_name='Number of Shares'),
        ),
    ]
