# Generated by Django 3.0.6 on 2020-06-09 09:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0017_auto_20200609_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[150, 150], upload_to='media/', verbose_name='Logo'),
        ),
    ]
