# Generated by Django 3.0.6 on 2020-06-09 09:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0018_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='media/', verbose_name='Person Image'),
        ),
    ]
