# Generated by Django 3.0.6 on 2020-06-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0019_auto_20200609_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bias',
            field=models.CharField(choices=[('#39E749', 'Most Right'), ('#3390E7', 'Right'), ('#E7E7E7', 'Neutral'), ('#E4E736', 'Left'), ('#E74C3C', 'Most Left')], default='#E7E7E7', max_length=10, verbose_name='Bias'),
        ),
    ]
