# Generated by Django 3.0.6 on 2020-06-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0020_news_bias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='bias',
            field=models.CharField(choices=[('2', 'Most Right'), ('1', 'Partly Right'), ('0', 'Neutral'), ('-1', 'Partly Left'), ('-2', 'Most Left')], default='0', max_length=10, verbose_name='Bias'),
        ),
    ]
