# Generated by Django 3.0.6 on 2020-06-18 00:19

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0021_auto_20200612_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalperson',
            options={'verbose_name': 'Legal Person', 'verbose_name_plural': 'Legal Persons'},
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='legal_role',
            field=models.ManyToManyField(related_name='legalperson_legal_role', to='Shenasa.LegalRole', verbose_name='Legal Key Person'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='news',
            field=models.ManyToManyField(related_name='legalperson_news', to='Shenasa.News', verbose_name='News'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='person_role',
            field=models.ManyToManyField(related_name='legalperson_person_role', to='Shenasa.PersonRole', verbose_name='Natural Key Person'),
        ),
        migrations.CreateModel(
            name='Brand1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[150, 150], upload_to='media/', verbose_name='Logo')),
                ('legal_role', models.ManyToManyField(related_name='brand1_legal_role', to='Shenasa.LegalRole', verbose_name='Legal Key Person')),
                ('news', models.ManyToManyField(related_name='brand1_news', to='Shenasa.News', verbose_name='News')),
                ('person_role', models.ManyToManyField(related_name='brand1_person_role', to='Shenasa.PersonRole', verbose_name='Natural Key Person')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
