# Generated by Django 3.0.6 on 2020-06-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0022_auto_20200618_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
