# Generated by Django 3.0.6 on 2020-06-18 00:47

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0023_delete_brand'),
    ]

    operations = [
        migrations.RenameModel('Brand1', 'Brand'),
    ]
