# Generated by Django 3.0.6 on 2020-06-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0024_auto_20200618_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='legalperson',
            options={'ordering': ['name'], 'verbose_name': 'Legal Person', 'verbose_name_plural': 'Legal Persons'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='legal_role',
            field=models.ManyToManyField(related_name='brand_legal_role', to='Shenasa.LegalRole', verbose_name='Legal Key Person'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='news',
            field=models.ManyToManyField(related_name='brand_news', to='Shenasa.News', verbose_name='News'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='person_role',
            field=models.ManyToManyField(related_name='brand_person_role', to='Shenasa.PersonRole', verbose_name='Natural Key Person'),
        ),
    ]
