# Generated by Django 3.0.6 on 2020-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0025_auto_20200619_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalrole',
            name='number_of_shares',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='number_of_shares',
        ),
        migrations.AddField(
            model_name='legalrole',
            name='number_of_stocks',
            field=models.IntegerField(default=0, verbose_name='Number of Stocks'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='number_of_stocks',
            field=models.IntegerField(default=0, verbose_name='Number of Stocks'),
        ),
    ]
