# Generated by Django 3.0.6 on 2020-06-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0026_auto_20200619_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='person_role',
            field=models.ManyToManyField(related_name='brand_person_role_last', to='Shenasa.PersonRole', verbose_name='Natural Key Person'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='person_role',
            field=models.ManyToManyField(related_name='legalperson_person_role_last', to='Shenasa.PersonRole', verbose_name='Natural Key Person'),
        ),
        migrations.CreateModel(
            name='LegalPersonPersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FN', 'Founder'), ('CH', 'Chairman'), ('IN', 'Investor'), ('IF', 'Foreign Investor'), ('IV', 'Venture Capital'), ('IA', 'Angel Investor'), ('ST', 'Stackholder'), ('AC', 'Accelerator'), ('OW', 'Owner'), ('CM', 'Chief Marketing Officer'), ('CC', 'Chief Communication Officer'), ('CE', 'Chief Executive Officer'), ('CT', 'Chief Technical Officer'), ('CF', 'Co Founder')], default='ST', max_length=10, verbose_name='Role')),
                ('number_of_stocks', models.IntegerField(default=0, verbose_name='Number of Stocks')),
                ('amount_of_investment', models.IntegerField(default=0, verbose_name='Amount of Investment (M rls)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shenasa.NaturalPerson', verbose_name='Person')),
                ('target_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shenasa.LegalPerson', verbose_name='Legal Person')),
            ],
            options={
                'verbose_name': 'Person Role',
                'verbose_name_plural': 'Person Roles',
                'ordering': ['person', 'role', 'target_person'],
                'abstract': False,
                'unique_together': {('person', 'target_person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='BrandPersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FN', 'Founder'), ('CH', 'Chairman'), ('IN', 'Investor'), ('IF', 'Foreign Investor'), ('IV', 'Venture Capital'), ('IA', 'Angel Investor'), ('ST', 'Stackholder'), ('AC', 'Accelerator'), ('OW', 'Owner'), ('CM', 'Chief Marketing Officer'), ('CC', 'Chief Communication Officer'), ('CE', 'Chief Executive Officer'), ('CT', 'Chief Technical Officer'), ('CF', 'Co Founder')], default='ST', max_length=10, verbose_name='Role')),
                ('number_of_stocks', models.IntegerField(default=0, verbose_name='Number of Stocks')),
                ('amount_of_investment', models.IntegerField(default=0, verbose_name='Amount of Investment (M rls)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shenasa.NaturalPerson', verbose_name='Person')),
                ('target_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shenasa.Brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Person Role',
                'verbose_name_plural': 'Person Roles',
                'ordering': ['person', 'role', 'target_person'],
                'abstract': False,
                'unique_together': {('person', 'target_person', 'role')},
            },
        ),
    ]
