# Generated by Django 3.0.6 on 2020-06-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0027_auto_20200620_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='person_role',
        ),
        migrations.RemoveField(
            model_name='legalperson',
            name='person_role',
        ),
        migrations.AlterField(
            model_name='brandpersonrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_person_role_person', to='Shenasa.NaturalPerson', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='brandpersonrole',
            name='target_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_person_role_target_person', to='Shenasa.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='legalpersonpersonrole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_person_role_person', to='Shenasa.NaturalPerson', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='legalpersonpersonrole',
            name='target_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_person_person_role_target_person', to='Shenasa.LegalPerson', verbose_name='Legal Person'),
        ),
        migrations.DeleteModel(
            name='PersonRole',
        ),
    ]
