# Generated by Django 3.0.6 on 2020-06-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0029_brandlegalrole_legalpersonlegalrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='legal_role',
        ),
        migrations.RemoveField(
            model_name='legalperson',
            name='legal_role',
        ),
        migrations.DeleteModel(
            name='LegalRole',
        ),
    ]
