# Generated by Django 3.0.6 on 2020-08-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shenasa', '0031_auto_20200621_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='', max_length=1000, unique=True, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.TextField(default='', max_length=200, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
